### ISSUE TITLE
Discussion: Desmos Profile Module

### ISSUE THREAD

**Issue by ryuash** [forbole/big-dipper-desmos#101]
tbd

**Comment by RiccardoM** [comment]
## Context
Inside Desmos, a `Profile` is just a custom implementation of the Cosmos interface `AccountI`. For this reason, all profile details will be retrieved using the legacy API `/auth/accounts/{address}` or the new `/cosmos/auth/v1beta1/accounts/{address}` endpoint.

The basic details that a profile will contain are outlined inside our documentation website [here](https://docs.desmos.network/developers/types/profiles/profile.html). 

## JSON structure
In order to allow BigDipper to access all the data in an easier way, I propose we use [DJuno](https://github.com/desmos-labs/djuno) to parse the profiles data and store them inside different tables, allowing to setup various relationships as well. 

The proposed JSON structure will look something like this: 

```json
{
  "dtag": "<User DTag>",
  "nickname": "<User Nickname>",
  "bio": "<User biography>",
  "pictures": {
    "cover": "<User cover picture>",
    "profile": "<User profile picture>"
  },
  "creation_time": "<Creation time>",
  "chains_links": [
    "<Chain Link object>"
  ],
  "application_links": [
    "<Application link object>"
  ]
}
```

#### Chain link object
Each chain link object will be formed as follows:
```json
{
  "address": "<Link address>",
  "proof": {
    "pub_key": "<Public key value>",
    "signature": "<Hex encoded signature>",
    "plain_text": "<Signed plain text>"
  },
  "chain_config": {
    "name": "<Chain name (eg. Desmos, Cosmos, etc)>"
  },
  "creation_time": "<Link creation time>"
}
```

### Application link object
Each application link will be formed as follows: 
```json
{
  "data": {
    "application": "<Name of the application (eg. Twitter, Instagram, etc)>",
    "username": "<Username used inside the application>"
  },
  "state": "<Link state>",
  "oracle_request": {
    "id": "<Request ID, searchable on the Band Protocol chain>",
    "oracle_script_id": "<ID of the oracle script used to verify the link, searchable on the Band Protocol chain>",
    "call_data": "<[Object] Call data sent to the oracle script, should be rendered as a raw object>",
    "client_id": "<ID of the client associated with the requet>"
  },
  "result": "<[Object] Link verification result, should be rendered as a raw object>",
  "creation_time": "<Link creation time>"
}
```

**Comment by ryuash** [comment]
@RiccardoM Is it safe to assume once they are inside `application_links` or `chains_links` their verification / link was a success?

**Comment by RiccardoM** [comment]
> @RiccardoM Is it safe to assume once they are inside `application_links` or `chains_links` their verification / link was a success?

It is safe to assume that once it's inside `chains_links`, the external chain link was a success. 

However, it is **not** safe to assume the same thing for `applications_links` because those require a multi-step process to be finalized. It's for this reason that each `applications_links` object has it's own `state` that tells whether the links is: 
- just initialized and the verification is still happening 
- a success (with the data to verify it) 
- a failure (with the associated error)
